### ISSUE TITLE
Suggestion: -targets option

### ISSUE THREAD

**Issue by syrius01** [halildz/wildPwn#1]
Hi,

First I would like to thank you for sharing this great script :) Would it be possible when you have some free time to add an option like "-targets targets.txt" which some wildfly servers would be in targets.txt ?

Thanks.

**Comment by hlldz** [comment]
Hi,

Thank you for suggestion! Yes, I will take care of the first opportunity and I will also make some performance improvements. Until then you can use the Nmap Scripts.
