### ISSUE TITLE
--port arg is invalid

### ISSUE THREAD

**Issue by syrius01** [halildz/wildPwn#4]
Hi,

Let me first thank you for sharing this awesome tool with the community :) I am currently trying to bruteforce some local servers running WildFly on port 8080 but it seems the argument '--port' is invalid since when I do "netstat -an" I see connections trying to connect on port 9990. I've confirmed that by looking at your source:

tryComb     = requests.post("http://" + target +":9990/management", auth=HTTPDigestAuth(str(username), str(password)))

Also, if there could be an argument like '--target-list wildfly_servers.txt' it would be very very useful :)

Thanks !

**Comment by hlldz** [comment]
Hi,

Thank you!

Sorry, I could not continue developing because I could not find time. :/ The tool does not currently support multiple targets, you can use the Nmap Scripts for that operation.
